module.exports = {
    Aqua: 'aqua',
    Black: 'black',
    Blue: 'blue',
    Brown: 'brown',
    DarkBlue: 'darkblue',
    DarkGray: 'darkgray',
    DarkGrey: 'darkgrey',
    DarkGreen: 'darkgreen',
    DarkRed: 'darkred',
    Gold: 'gold',
    Green: 'green',
    Gray: 'gray',
    Grey: 'grey',
    Magenta: 'magenta',
    Orange: 'orange',
    Pink: 'pink',
    Purple: 'purple',
    Red: 'red',
    Rose: 'rose',
    White: 'white',
    Yellow: 'yellow'
};
